In [29]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('pc_dataset.csv')
df.head()

model model.1  drive_size  ram processor   gen  \
0      EliteBook 2560p     hdd         320    4        i7   2.0   
1       Razer Blade 15     ssd        1000   16        i7   8.0   
2  Acer Nitro AN515-55     ssd         256    8        i5  10.0   
3       HP Folio 9480m     hdd         500    8        i5   4.0   
4   HP EliteBook 8440p     hdd         320    4        i5   1.0   

   processor_speed  screen_size  screen_r_width  screen_r_height  \
0              2.7         12.5            1366              768   
1              2.6         15.6            1920             1080   
2              2.5         15.0            1920             1080   
3              2.6         14.0            1600              900   
4              2.6         14.0            1366              768   

   touch_screen  keyboard_light  hdmi   price  
0             0               0     0  100000  
1             0               1     1  678000  
2             0               1     1  485000  
3             0               1     0  155000  
4             0               0     0   85000

In [30]:
df.isnull().sum()

model              0
model.1            0
drive_size         0
ram                0
processor          0
gen                0
processor_speed    0
screen_size        0
screen_r_width     0
screen_r_height    0
touch_screen       0
keyboard_light     0
hdmi               0
price              0
dtype: int64

In [31]:
df.shape

(201, 14)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   model            201 non-null    object 
 1   model.1          201 non-null    object 
 2   drive_size       201 non-null    int64  
 3   ram              201 non-null    int64  
 4   processor        201 non-null    object 
 5   gen              201 non-null    float64
 6   processor_speed  201 non-null    float64
 7   screen_size      201 non-null    float64
 8   screen_r_width   201 non-null    int64  
 9   screen_r_height  201 non-null    int64  
 10  touch_screen     201 non-null    int64  
 11  keyboard_light   201 non-null    int64  
 12  hdmi             201 non-null    int64  
 13  price            201 non-null    int64  
dtypes: float64(3), int64(8), object(3)
memory usage: 22.1+ KB


In [76]:
print(df['hdmi'].unique())

[0 1]


In [34]:
print(df['model.1'].unique())
print(df['processor'].unique())


['hdd' 'ssd']
['i7' 'i5' 'Ryzen 5' 'i3' 'Xeon' 'Ryzen 7' 'atom' 'A6' 'celeron' '2 duo'
 'Ryzen 9' 'pentium' 'E1']


In [35]:
print(df['model'].unique())

['EliteBook 2560p' 'Razer Blade 15' 'Acer Nitro AN515-55' 'HP Folio 9480m'
 'HP EliteBook 8440p' 'ASUS ZenBook(UX325EA)' 'HP Pavilion ' 'HP Zbook G3'
 'Hp Zbook 15u G6' 'HP 840 G3' 'DELL XPS 15 9560'
 'Acer Predator helios 300' 'HP EliteBook X360 1030 G2' 'Lenovo Region 5'
 'SAMSUNG 730QCJ' 'DELL XPS 13(9360)' 'HP Probook 445 G6'
 'HP Pro X2 612 G1' 'ASUS G551 JM' 'LENOVO YOGA' 'LENOVO THINKPAD T490'
 'DELL Precision 7530' 'Hp Laptop 15' 'LENOVO Thinkpad E15'
 'Dell Latitude E3380' 'HP Elite 1012' 'Dell Inspiron 7415' 'ACER NITRO 5'
 'DELL PRECISION 7530' 'LENOVO THINKPAD P73' 'DELL ALIENWARE M15 R2'
 'HP ELITE BOOK X360 1012 G1' 'HP ELITE BOOK 1012 G2' 'HP PRO BOOK 450 G3'
 'HP Envy x360' 'Dell Inspiron 5593' 'Hp Elitebook 850 G6'
 'SONT PCG VPCC W21FX' 'HP ELITEBOOK 650 G5' 'Dell Latitude 5400'
 'Lenovo Thinkpad T420i' 'HP Omen 16' 'LENOVE G470'
 'Hp Zbook Firefly 15 G7 ' 'SONY PGV VPCEB29FJ' 'TRANSFORMATION BOOK '
 'MACBOOK PRO' 'MSi Katana Gf66' 'HP PROBOOK 645' 'Dell G15 5510' 'HP

In [36]:
from sklearn.preprocessing import LabelEncoder
le_model = LabelEncoder()
df['model'] = le_model.fit_transform(df['model'])
df["model"].unique()

array([ 71, 186,  11, 103,  86,   7, 109, 130, 135,  77,  33,  12,  87,
       154, 189,  31, 117, 113,   3, 145, 142,  27, 134, 143,  59,  82,
        48,   1,  26, 140,  22,  79,  78, 107, 102,  46, 133, 191,  80,
        51, 162, 106, 138, 136, 192, 195, 171, 177, 108,  35,  76, 197,
        24, 144, 184,  28, 155, 141, 183,  25, 139, 131,  68,  58, 111,
        93,  90,  36, 160, 172,  88, 132, 146, 104,  89,  44, 149,  45,
       190, 178, 152,  47,  56,   4, 173,  17,  65,  15, 159, 165,  67,
         8, 150,  13,  37,  10, 179,  94, 120, 125,   6,  81,  19, 169,
       147,  70, 151,  73, 196, 158, 122,  55,  60, 174,  52,  18,  53,
        41,   2, 198,   0, 185, 137, 194, 161,  98,  43,  38,  85, 129,
       101, 148,   9, 164, 112,  75, 156,  99,   5,  20, 114,  32, 175,
        96,  64, 181,  14, 119,  62, 187, 166, 176, 153,  69, 128,  29,
        74,  97,  30,  42, 188, 118,  40, 168,  63,  66,  49, 182,  16,
       170,  57, 121, 163,  54, 157, 115, 193,  72,  92,  39, 10

In [37]:
le_model_1 = LabelEncoder()
df['model.1'] = le_model_1.fit_transform(df['model.1'])
df["model.1"].unique()

array([0, 1])

In [38]:
le_processor = LabelEncoder()
df['processor'] = le_processor.fit_transform(df['processor'])
df["processor"].unique()

array([11, 10,  3,  9,  6,  4,  7,  1,  8,  0,  5, 12,  2])

In [39]:
X = df.drop("price", axis=1)
y = df["price"]

In [40]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)

LinearRegression()

In [41]:
y_pred = linear_reg.predict(X)

In [42]:
from sklearn.metrics import mean_squared_error, mean_absolute_error,mean_absolute_percentage_error,r2_score
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))
erro2 = mean_absolute_percentage_error(y,y_pred)
acuuracy = r2_score(y,y_pred)

In [43]:
print(acuuracy)
print(error)
print(erro2)

0.6540514981844385
97942.55128556512
0.25209268694223225


In [44]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X, y.values)

DecisionTreeRegressor(random_state=0)

In [45]:
y_pred = dec_tree_reg.predict(X)

In [46]:
error2 = np.sqrt(mean_squared_error(y, y_pred))
erro22 = mean_absolute_percentage_error(y,y_pred)
acuuracy2 = r2_score(y,y_pred)

In [47]:
print(acuuracy2)
print(error2)
print(erro22)

1.0
0.0
0.0


In [48]:
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, y.values)

RandomForestRegressor(random_state=0)

In [49]:
y_pred = random_forest_reg.predict(X)

In [50]:
error2 = np.sqrt(mean_squared_error(y, y_pred))
erro22 = mean_absolute_percentage_error(y,y_pred)
acuuracy2 = r2_score(y,y_pred)

In [51]:
print(acuuracy2)
print(error2)
print(erro22)

0.9408502986302402
40498.78216337397
0.07955241322571917


In [52]:
from sklearn.model_selection import GridSearchCV

max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = RandomForestRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)

GridSearchCV(estimator=RandomForestRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [53]:
regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))

40,498.78


In [54]:
X

model  model.1  drive_size  ram  processor   gen  processor_speed  \
0       71        0         320    4         11   2.0              2.7   
1      186        1        1000   16         11   8.0              2.6   
2       11        1         256    8         10  10.0              2.5   
3      103        0         500    8         10   4.0              2.6   
4       86        0         320    4         10   1.0              2.6   
..     ...      ...         ...  ...        ...   ...              ...   
196     91        0         500    8         11   6.0              2.6   
197     21        1         512   16         11   8.0              2.3   
198     34        1         180   16         11   7.0              2.9   
199     84        1         256    8         10   6.0              2.0   
200     83        1         512    8         10   8.0              2.6   

     screen_size  screen_r_width  screen_r_height  touch_screen  \
0           12.5            1366              768             0   
1           15.6            1920             1080             0   
2           15.0            1920             1080             0   
3           14.0            1600              900             0   
4           14.0            1366              768             0   
..           ...             ...              ...           ...   
196         12.5            1920             1080             0   
197         15.6            1920             1080             0   
198         17.3            1920             1080             0   
199         14.0            1920             1080             1   
200         13.0            1920             1080             1   

     keyboard_light  hdmi  
0                 0     0  
1                 1     1  
2                 1     1  
3                 1     0  
4                 0     0  
..              ...   ...  
196               1     0  
197               1     1  
198               1     1  
199               1     1  
200               1     1  

[201 rows x 13 columns]

In [55]:
#model	model.1	drive_size	ram	processor	gen	processor_speed	screen_size	screen_r_width	screen_r_height	touch_screen	keyboard_light	hdmi

In [56]:
X = np.array([['EliteBook 2560p','hdd','320',4,'i7',2.0,'2.7',12.5,'1366','768',0.0,0.0,0.0	]])
X

array([['EliteBook 2560p', 'hdd', '320', '4', 'i7', '2.0', '2.7', '12.5',
        '1366', '768', '0.0', '0.0', '0.0']], dtype='<U32')

In [57]:
X[:, 0] = le_model.transform(X[:,0])
X[:, 1] = le_model_1.transform(X[:,1])
X[:, 4] = le_processor.transform(X[:,4])
X = X.astype(float)
X


array([[  71. ,    0. ,  320. ,    4. ,   11. ,    2. ,    2.7,   12.5,
        1366. ,  768. ,    0. ,    0. ,    0. ]])

In [58]:
y_pred = regressor.predict(X)
y_pred

c:\Users\Simeon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([101640.])

In [59]:
import pickle

In [63]:
data = {"model": regressor, "le_model": le_model, "le_model_1": le_model_1,"le_processor": le_processor}
with open('steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [64]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]

In [65]:
y_pred = regressor_loaded.predict(X)
y_pred

c:\Users\Simeon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([101640.])