In [2]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('pc_dataset.csv')
df.head()

model model.1 drive_size  ram processor   gen  \
0      EliteBook 2560p     hdd        320    4        i7   2.0   
1       Razer Blade 15     ssd        NaN   16        i7   8.0   
2  Acer Nitro AN515-55     ssd        256    8        i5  10.0   
3       HP Folio 9480m     hdd        500    8        i5   4.0   
4   HP EliteBook 8440p     hdd        320    4        i5   1.0   

  processor_speed  screen_size screen_r_width screen_r_height  touch_screen  \
0             2.7         12.5           1366             768           0.0   
1             NaN         15.6           1920            1080           0.0   
2             2.5         15.0           1920            1080           0.0   
3             2.6         14.0           1600             900           0.0   
4             2.6         14.0           1366             768           0.0   

   keyboard_light  hdmi   price  
0             0.0   0.0  100000  
1             1.0   1.0  678000  
2             1.0   1.0  485000  
3             1.0   0.0  155000  
4             0.0   0.0   85000

In [59]:
df.isnull().sum()

model               1
model.1             0
drive_size          1
ram                 0
processor           0
gen                27
processor_speed    30
screen_size         6
screen_r_width     39
screen_r_height    39
touch_screen        7
keyboard_light      6
hdmi                5
price               0
dtype: int64

In [60]:
df.shape

(202, 14)

In [61]:
df['model'].fillna('not specified',inplace=True)

In [62]:
df.isnull().sum()

model               0
model.1             0
drive_size          1
ram                 0
processor           0
gen                27
processor_speed    30
screen_size         6
screen_r_width     39
screen_r_height    39
touch_screen        7
keyboard_light      6
hdmi                5
price               0
dtype: int64

In [4]:
df.fillna(0,inplace=True)

In [64]:
df.isnull().sum()

model              0
model.1            0
drive_size         0
ram                0
processor          0
gen                0
processor_speed    0
screen_size        0
screen_r_width     0
screen_r_height    0
touch_screen       0
keyboard_light     0
hdmi               0
price              0
dtype: int64

In [65]:
#df['screen_r_height'].unique()
df.replace({'screen_r_height':0,'screen_r_width':0},inplace=True)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   model            202 non-null    object 
 1   model.1          202 non-null    object 
 2   drive_size       202 non-null    object 
 3   ram              202 non-null    int64  
 4   processor        202 non-null    object 
 5   gen              202 non-null    float64
 6   processor_speed  202 non-null    object 
 7   screen_size      202 non-null    float64
 8   screen_r_width   202 non-null    object 
 9   screen_r_height  202 non-null    object 
 10  touch_screen     202 non-null    float64
 11  keyboard_light   202 non-null    float64
 12  hdmi             202 non-null    float64
 13  price            202 non-null    int64  
dtypes: float64(5), int64(2), object(7)
memory usage: 22.2+ KB


In [76]:
df['screen_size'].replace({0:'0'},inplace=True)

In [5]:
print(df['gen'].unique())

[ 2.  8. 10.  4.  1. 11.  9.  6.  7.  5.  3.  0.]


In [68]:
print(df['model.1'].unique())
print(df['drive_size'].unique())
print(df['processor'].unique())
print(df['processor_speed'].unique())
print(df['screen_r_width'].unique())
print(df['screen_r_height'].unique())

['hdd' 'ssd' 'sdd' 'SSD' 'hhd']
['320' 0 '256' '500' '512' '1000' '1TB' '128' '64' '32' '180' '51GB' '250'
 '120']
['i7' 'i5' 'AMD' 'i3' 'Xeon' 'atom' 'A6' 'celeron' '2 duo' 'pentium' 'E1']
['2.7' 0 '2.5' '2.6' '3.8' '2.4' '1.99' '2.8' '1.6' '2' '2.9' '1.5' '1.8'
 '2.2' '3.1' '2.1' '1.44' '2..6' '1.3' '1.9' '2.13' '2.3' '4.7' '1.61'
 '1.33' '3.3' '1' '4.2' '2.67' '4' '1.35' '1.7' '3.6' '3.2' '2.53' '3'
 '4.9' '4.3' '4.1' '1.2']
['1366' '1920' '1600' '3200' '3840' '2736' '1280' '2560' 0 '3480']
['768' '1080' '900' '1800' '2160' '1280' '1824' '800' '1600' '0']


In [69]:
print(df['model'].unique())

['EliteBook 2560p' 'Razer Blade 15' 'Acer Nitro AN515-55' 'HP Folio 9480m'
 'HP EliteBook 8440p' 'ASUS ZenBook(UX325EA)' 'HP Pavilion ' 'HP Zbook G3'
 'Hp Zbook 15u G6' 'HP 840 G3' 'DELL XPS 15 9560'
 'Acer Predator helios 300' 'HP EliteBook X360 1030 G2' 'Lenovo Region 5'
 'SAMSUNG 730QCJ' 'DELL XPS 13(9360)' 'HP Probook 445 G6'
 'HP Pro X2 612 G1' 'ASUS G551 JM' 'LENOVO YOGA' 'LENOVO THINKPAD T490'
 'DELL Precision 7530' 'Hp Laptop 15' 'LENOVO Thinkpad E15'
 'Dell Latitude E3380' 'HP Elite 1012' 'Dell Inspiron 7415' 'ACER NITRO 5'
 'DELL PRECISION 7530' 'LENOVO THINKPAD P73' 'DELL ALIENWARE M15 R2'
 'HP ELITE BOOK X360 1012 G1' 'HP ELITE BOOK 1012 G2' 'HP PRO BOOK 450 G3'
 'HP Envy x360' 'Dell Inspiron 5593' 'Hp Elitebook 850 G6'
 'SONT PCG VPCC W21FX' 'HP ELITEBOOK 650 G5' 'Dell Latitude 5400'
 'Lenovo Thinkpad T420i' 'HP Omen 16' 'LENOVE G470'
 'Hp Zbook Firefly 15 G7 ' 'SONY PGV VPCEB29FJ' 'TRANSFORMATION BOOK '
 'MACBOOK PRO' 'MSi Katana Gf66' 'HP PROBOOK 645' 'Dell G15 5510' 'HP

In [70]:
from sklearn.preprocessing import LabelEncoder
le_model = LabelEncoder()
df['model'] = le_model.fit_transform(df['model'])
df["model"].unique()

array([ 72, 187,  11, 104,  87,   7, 110, 131, 136,  78,  33,  12,  88,
       155, 190,  31, 118, 114,   3, 146, 143,  27, 135, 144,  59,  83,
        48,   1,  26, 141,  22,  80,  79, 108, 103,  46, 134, 192,  81,
        51, 163, 107, 139, 137, 193, 196, 172, 178, 109,  35,  77, 198,
        24, 145, 185,  28, 156, 142, 184,  25, 140, 132,  69,  58, 112,
        94,  91,  36, 161, 173,  89, 133, 147, 105,  90,  44, 150,  45,
       191, 179, 153,  47,  56,   4, 174,  17,  66,  15, 160, 166,  68,
         8, 151,  13,  37,  10, 180,  95, 121, 126,   6,  82,  19, 170,
       148,  71, 152,  74, 197, 159, 123,  55,  60, 175,  52,  18,  53,
        41,   2, 199,   0, 186, 138, 195, 162,  99,  43,  38,  86, 130,
       102, 149,   9, 165, 113,  76, 157, 100,   5,  20, 115,  32, 176,
        97,  65, 182,  14, 120,  62, 188, 167, 177, 154,  70, 129,  29,
        75,  98,  30,  42, 189, 119,  40, 169,  64,  67,  49, 183,  16,
       171,  57, 122, 164,  54, 158, 116, 194,  73,  93,  39, 10

In [71]:
le_model_1 = LabelEncoder()
df['model.1'] = le_model_1.fit_transform(df['model.1'])
df["model.1"].unique()

array([1, 4, 3, 0, 2])

In [77]:
le_drive_size = LabelEncoder()
df['drive_size'] = le_drive_size.fit_transform(df['drive_size'])
df["drive_size"].unique()

array([ 9,  0,  7, 10, 11,  1,  5,  3, 13,  8,  4, 12,  6,  2])

In [78]:
le_processor = LabelEncoder()
df['processor'] = le_processor.fit_transform(df['processor'])
df["processor"].unique()

array([ 9,  8,  2,  7,  4,  5,  1,  6,  0, 10,  3])

In [79]:
le_processor_speed = LabelEncoder()
df['processor_speed'] = le_processor_speed.fit_transform(df['processor_speed'])
df["processor_speed"].unique()

array([25,  0, 21, 23, 33, 20, 13, 26,  8, 14, 27,  7, 11, 18, 29, 16,  6,
       15,  3, 12, 17, 19, 38,  9,  4, 31,  1, 36, 24, 34,  5, 10, 32, 30,
       22, 28, 39, 37, 35,  2])

In [80]:
le_screen_r_width = LabelEncoder()
df['screen_r_width'] = le_screen_r_width.fit_transform(df['screen_r_width'])
df["screen_r_width"].unique()

array([2, 4, 3, 7, 9, 6, 1, 5, 0, 8])

In [81]:
le_screen_r_height = LabelEncoder()
df['screen_r_height'] = le_screen_r_height.fit_transform(df['screen_r_height'])
df["screen_r_height"].unique()

array([7, 1, 9, 4, 6, 2, 5, 8, 3, 0])

In [82]:
X = df.drop("price", axis=1)
y = df["price"]

In [83]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)

LinearRegression()

In [84]:
y_pred = linear_reg.predict(X)

In [85]:
from sklearn.metrics import mean_squared_error, mean_absolute_error,mean_absolute_percentage_error,r2_score
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))
erro2 = mean_absolute_percentage_error(y,y_pred)
acuuracy = r2_score(y,y_pred)

In [86]:
print(acuuracy)
print(error)
print(erro2)

0.5893582081143498
106445.76255236533
0.2507610384259588


In [87]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X, y.values)

DecisionTreeRegressor(random_state=0)

In [88]:
y_pred = dec_tree_reg.predict(X)

In [89]:
error2 = np.sqrt(mean_squared_error(y, y_pred))
erro22 = mean_absolute_percentage_error(y,y_pred)
acuuracy2 = r2_score(y,y_pred)

In [90]:
print(acuuracy2)
print(error2)
print(erro22)

1.0
0.0
0.0


In [91]:
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, y.values)

RandomForestRegressor(random_state=0)

In [92]:
y_pred = random_forest_reg.predict(X)

In [93]:
error2 = np.sqrt(mean_squared_error(y, y_pred))
erro22 = mean_absolute_percentage_error(y,y_pred)
acuuracy2 = r2_score(y,y_pred)

In [94]:
print(acuuracy2)
print(error2)
print(erro22)

0.9444179844933479
39161.91765043441
0.08170579043138018


In [95]:
from sklearn.model_selection import GridSearchCV

max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = RandomForestRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)

GridSearchCV(estimator=RandomForestRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [96]:
regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))

39,315.93


In [97]:
X

model  model.1  drive_size  ram  processor   gen  processor_speed  \
0       72        1           9    4          9   2.0               25   
1      187        4           0   16          9   8.0                0   
2       11        4           7    8          8  10.0               21   
3      104        1          10    8          8   4.0               23   
4       87        1           9    4          8   1.0               23   
..     ...      ...         ...  ...        ...   ...              ...   
197     21        0          11   16          9   0.0               19   
198     34        4           4   16          9   7.0               27   
199    200        4           7   16          9   8.0               12   
200     85        4           7    8          8   6.0               14   
201     84        4          11    8          8   8.0               23   

     screen_size  screen_r_width  screen_r_height  touch_screen  \
0           12.5               2                7           0.0   
1           15.6               4                1           0.0   
2           15.0               4                1           0.0   
3           14.0               3                9           0.0   
4           14.0               2                7           0.0   
..           ...             ...              ...           ...   
197         15.6               4                1           0.0   
198         17.3               4                1           0.0   
199         14.0               4                1           1.0   
200         14.0               4                1           1.0   
201         13.0               4                1           1.0   

     keyboard_light  hdmi  
0               0.0   0.0  
1               1.0   1.0  
2               1.0   1.0  
3               1.0   0.0  
4               0.0   0.0  
..              ...   ...  
197             1.0   1.0  
198             1.0   1.0  
199             1.0   1.0  
200             1.0   1.0  
201             1.0   1.0  

[202 rows x 13 columns]

In [98]:
#model	model.1	drive_size	ram	processor	gen	processor_speed	screen_size	screen_r_width	screen_r_height	touch_screen	keyboard_light	hdmi

In [99]:
X = np.array([['EliteBook 2560p','hdd','320',4,'i7',2.0,'2.7',12.5,'1366','768',0.0,0.0,0.0	]])
X

array([['EliteBook 2560p', 'hdd', '320', '4', 'i7', '2.0', '2.7', '12.5',
        '1366', '768', '0.0', '0.0', '0.0']], dtype='<U32')

In [100]:
X[:, 0] = le_model.transform(X[:,0])
X[:, 1] = le_model_1.transform(X[:,1])
X[:, 2] = le_drive_size.transform(X[:,2])
X[:, 4] = le_processor.transform(X[:,4])
X[:, 6] = le_processor_speed.transform(X[:,6])
X[:, 8] = le_screen_r_width.transform(X[:,8])
X[:, 9] = le_screen_r_height.transform(X[:,9])
X = X.astype(float)
X


array([[72. ,  1. ,  9. ,  4. ,  9. ,  2. , 25. , 12.5,  2. ,  7. ,  0. ,
         0. ,  0. ]])

In [101]:
y_pred = regressor.predict(X)
y_pred

c:\Users\Simeon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([96060.])

In [102]:
import pickle

In [103]:
data = {"model": regressor, "le_model": le_model, "le_model_1": le_model_1,"le_drive_size": le_drive_size,"le_processor": le_processor,"le_processor_speed": le_processor_speed,"le_screen_r_width": le_screen_r_width,"le_screen_r_height": le_screen_r_height}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [104]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]

In [105]:
y_pred = regressor_loaded.predict(X)
y_pred

c:\Users\Simeon\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([96060.])